<a href="https://colab.research.google.com/github/Mayanzev/Telecom/blob/main/lab7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
PI2 = 2 * np.pi

# **Упражнение 7.1**
В блокноте для этой главы, chap07.ipynb, представлены дополнительные примеры и пояснения. Прочитайте блокнот и запустите код.

# **Упражнение 7.2**
Необходимо выполнить алгоритм быстрого преобразования Фурье (БПФ), ключом к БПФ является лемма Дэниелсона-Ланцоша, которая предлагает рекурсивный алгоритм для ДПФ. Полное описание представлено в методичке.

Возьмем некоторый тестовый пример.

In [3]:
ys = [-0.2, 0.3, 0.7, -0.4]
hs = np.fft.fft(ys)
print(hs)

[ 0.4+0.j  -0.9-0.7j  0.6+0.j  -0.9+0.7j]


In [4]:
def dft(ys):
    N = len(ys)
    ts = np.arange(N) / N
    freqs = np.arange(N)
    args = np.outer(ts, freqs)
    M = np.exp(1j * PI2 * args)
    amps = M.conj().transpose().dot(ys)
    return amps

In [6]:
hs2 = dft(ys)
hs2

array([ 0.4+0.00000000e+00j, -0.9-7.00000000e-01j,  0.6+2.81668764e-16j,
       -0.9+7.00000000e-01j])

Начнем с нерекурсивной версии, разделив элементы.

In [11]:
def my_fft(ys):
  N = len(ys)
  He = dft(ys[::2])
  Ho = dft(ys[1::2])

  ns = np.arange(N)
  W = np.exp(-1j * PI2 * ns / N)

  return np.tile(He, 2) + W * np.tile(Ho, 2)

ys[::2], ys[1::2], my_fft(ys)

([-0.2, 0.7],
 [0.3, -0.4],
 array([ 0.4+0.0000000e+00j, -0.9-7.0000000e-01j,  0.6+1.2246468e-17j,
        -0.9+7.0000000e-01j]))

Теперь сделаем рекурсивный метод.

In [12]:
def my_fft(ys):
    N = len(ys)
    if N == 1:
        return ys

    He = my_fft(ys[::2])
    Ho = my_fft(ys[1::2])

    ns = np.arange(N)
    W = np.exp(-1j * PI2 * ns / N)

    return np.tile(He, 2) + W * np.tile(Ho, 2)

ys[::2], ys[1::2], my_fft(ys)

([-0.2, 0.7],
 [0.3, -0.4],
 array([ 0.4+0.0000000e+00j, -0.9-7.0000000e-01j,  0.6+1.2246468e-17j,
        -0.9+7.0000000e-01j]))